"""fixed model result2

Revision ID: 902e0f0a7f9e
Revises: 1d1bcf05254c
Create Date: 2024-01-23 21:00:04.321961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902e0f0a7f9e'
down_revision: Union[str, None] = '1d1bcf05254c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
