"""fixed model result3

Revision ID: de9c3188e10f
Revises: 902e0f0a7f9e
Create Date: 2024-01-23 21:09:09.912145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9c3188e10f'
down_revision: Union[str, None] = '902e0f0a7f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detection_result_pipeline_id_fkey', 'detection_result', type_='foreignkey')
    op.drop_column('detection_result', 'pipeline_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_result', sa.Column('pipeline_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('detection_result_pipeline_id_fkey', 'detection_result', 'pipeline', ['pipeline_id'], ['id'])
    # ### end Alembic commands ###
